//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace senia1._2.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ToDoEntities1 : DbContext
    {
        public ToDoEntities1()
            : base("name=ToDoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<List> List { get; set; }
        public virtual DbSet<ListsUser> ListsUser { get; set; }
        public virtual DbSet<Task> Task { get; set; }
        public virtual DbSet<TasksList> TasksList { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
